### ISSUE TITLE
Login mask username field does not get replaced

### ISSUE THREAD

**Issue by wirepatch** [meredrica/nodebb-plugin-office-ldap#5]
Request for help!

I'm using current nobebb 18.4 and did configure the `User LDAP Query` filter field `(uid=%uid)`. Unfortunately `'%uid'`  is not being replaced by `username` from login screen as being set in Line 168 of index.js. On the OpenLdap server side I see:

```
SRCH base="ou=userlist,dc=hdm-stuttgart,dc=de" scope=2 deref=0 filter="(uid=%uid)"
```

rather then (In my username goik case):

```
SRCH base="ou=userlist,dc=hdm-stuttgart,dc=de" scope=2 deref=0 filter="(uid=goik)"
```

**Comment by wirepatch** [comment]
Found the error myself by source code inspection. Replacement proposal:

```
placeholder="(&(|(objectclass=inetOrgPerson))(uid=%uid))
```

by 

```
placeholder="(&(|(objectclass=inetOrgPerson))(uid=%sAMAccountName))
```

**Comment by meredrica** [comment]
That is not a fix. That's Microsoft LDAP server that's not using the correct property. I'm not going to change this.
There is a fork of somebody that changed this single property.

**Comment by wirepatch** [comment]
True! I was installing nodebb-plugin-yingying-ldap rather than nodebb-plugin-open-ldap. Unfortunately the author did not change the project reference so the plugin overview in nodebb still points to https://github.com/blair-0/nodebb-plugin-open-ldap#readme. And the author did not change the placeholder value accordingly. Sorry for my fault screwing up things!
