### ISSUE TITLE
Avoiding E-Mail confirmation on first login

### ISSUE THREAD

**Issue by wirepatch** [meredrica/nodebb-plugin-office-ldap#7]
Using `nodebb-plugin-sso-open-ldap` on each user's first login a confirmation e-mail is being sent to the directory entries `mail`attribute value.

Since directory data is being considered valid this step is actually confusing: Users do conceive our internal Nodebb forum  server as part of the organization. Self registration is prohibited by configuration anyway  hence e-mail confirmations are pointless.

Is there a way automatically marking newly LDAP created Nodebb user accounts as `confirmed` among with their corresponding e-mail addresses?

I've opened a corresponding request at the  [NodeBB Technical Support community forum](https://community.nodebb.org/topic/16082/avoiding-e-mail-verification-in-case-of-ldap-login) without success so far.

**Comment by meredrica** [comment]
The plugin does not perform any email sending,it's most likely your nodebb config. The plugin creates and activates a new user account when somebody logs in for the first time. Maybe check the nodebb settings for this.
